"""create Usuario table

Revision ID: 76930ac03bbc
Revises: 
Create Date: 2023-02-16 16:07:21.752212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76930ac03bbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_dominio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_dominio', sa.String(), nullable=False),
    sa.Column('tipo_dominio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_dominio')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False, unique=True),
    sa.Column('nome_cliente', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('forma_pagamento', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('plano', sa.Integer(), nullable=True),
    sa.Column('tipo_usuario', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['forma_pagamento'], ['tb_dominio.id'], ),
    sa.ForeignKeyConstraint(['plano'], ['tb_dominio.id'], ),
    sa.ForeignKeyConstraint(['tipo_usuario'], ['tb_dominio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_cliente')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario')
    op.drop_table('tb_dominio')
    # ### end Alembic commands ###
