"""finalizando modelos

Revision ID: 3982e1f1e746
Revises: 76930ac03bbc
Create Date: 2023-02-18 13:45:20.788556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3982e1f1e746'
down_revision = '76930ac03bbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_pagamento',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cpf_usuario', sa.String(), nullable=False),
                    sa.Column('data_vencimento', sa.String(), nullable=True),
                    sa.Column('forma_pagamento', sa.Integer(), nullable=False),
                    sa.Column('valor_pagamento', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=True),
                    sa.Column('updated_by', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['forma_pagamento'], ['tb_dominio.id'], ),
                    sa.ForeignKeyConstraint(['cpf_usuario'], ['tb_usuario.cpf'], ),
                    )
    op.create_table('tb_politicas_pagamentos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('taxa_juros', sa.BigInteger(), nullable=False),
                    sa.Column('dias_vencidos', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=True),
                    sa.Column('updated_by', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_table('tb_treino',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cpf_usuario', sa.String(), nullable=False),
                    sa.Column('nome_exercicio', sa.String(), nullable=True),
                    sa.Column('series', sa.Integer(), nullable=False),
                    sa.Column('repeticoes', sa.Integer(), nullable=True),
                    sa.Column('data_fim', sa.DateTime(), nullable=False),
                    sa.Column('modalidade', sa.Integer(), nullable=True),
                    sa.Column('frequencia', sa.Integer(), nullable=False),
                    sa.Column('carga', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=True),
                    sa.Column('updated_by', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['modalidade'], ['tb_dominio.id'], ),
                    sa.ForeignKeyConstraint(['cpf_usuario'], ['tb_usuario.cpf'], ),
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_politicas_pagamentos')
    op.drop_table('tb_politicas_pagamentos')
    op.drop_table('tb_treino')
    # ### end Alembic commands ###
