"""adicionando tabela de administrador

Revision ID: 01644e998b19
Revises: 3982e1f1e746
Create Date: 2023-03-13 22:02:09.467931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01644e998b19'
down_revision = '3982e1f1e746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_administrador',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(), nullable=False),
                    sa.Column('data_nascimento', sa.String(), nullable=False),
                    sa.Column('endereco', sa.String(), nullable=False),
                    sa.Column('telefone', sa.String(), nullable=False),
                    sa.Column('ativo', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=True),
                    sa.Column('updated_by', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('tb_treino')
    op.drop_table('tb_pagamento')
    op.drop_table('tb_politicas_pagamentos')
    op.alter_column('tb_usuario', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_treino')
    op.drop_table('tb_pagamento')
    op.drop_table('tb_politicas_pagamentos')
    op.alter_column('tb_usuario', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
