"""adicionando coluna de senha

Revision ID: e599d04496de
Revises: 01644e998b19
Create Date: 2023-03-13 22:07:56.442861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, String
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e599d04496de'
down_revision = '01644e998b19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_administrador', Column('password', String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_administrador', Column('password', String()))
    # ### end Alembic commands ###
