"""adicionando coluna

Revision ID: 77a208ca6759
Revises: e599d04496de
Create Date: 2023-03-14 21:39:37.470964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, String
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77a208ca6759'
down_revision = 'e599d04496de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_administrador', Column('email', String(), unique=True))
    op.alter_column('tb_administrador', 'nome', unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_administrador', Column('email', String(), unique=True))
    op.alter_column('tb_administrador', 'nome', unique=False)
    # ### end Alembic commands ###
