"""geração de coluna de permissão

Revision ID: fb05451280f9
Revises: 09171ae068e7
Create Date: 2023-04-13 22:55:23.984428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Integer
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb05451280f9'
down_revision = '09171ae068e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_administrador', Column('nivel_permissao', Integer()))
    sa.ForeignKeyConstraint(['nivel_permissao'], ['tb_dominio.id'], )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_administrador', Column('nivel_permissao', Integer()))
    sa.ForeignKeyConstraint(['nivel_permissao'], ['tb_dominio.id'], )

