"""excluindo coluna valor

Revision ID: ec24b1ea1b87
Revises: fb05451280f9
Create Date: 2023-04-14 22:03:20.222981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec24b1ea1b87'
down_revision = 'fb05451280f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_pagamento', 'valor_pagamento')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_pagamento', 'valor_pagamento')